version: '3'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G